- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/constants/SdcSchoolCollectionStudentValidationIssueTypeCode.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/constants/v1/URL.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/CodeTableAPIController.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/endpoint/v1/CodeTableAPIEndpoint.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/mappers/v1/CodeTableMapper.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/model/v1/SpecialEducationCategoryCodeEntity.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/repository/v1/SpecialEducationCategoryRepository.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/impl/AdultStudentRule.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/impl/GradeCodeRule.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/impl/NonHSGradeRule.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/CodeTableService.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/ValidationRulesService.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/BaseStudentDataCollectionAPITest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/rules/RulesProcessorTest.java
> EDX-1073: Validation rule + Unit test

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/batch/processor/SdcBatchFileProcessor.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/batch/validator/SdcFileValidator.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcFileControllerTest.java
- api/src/test/resources/sample-malformed-long-content.txt
- api/src/test/resources/sample-malformed-long-header.txt
- api/src/test/resources/sample-malformed-long-trailer.txt
- api/src/test/resources/sample-malformed-short-content.txt
- api/src/test/resources/sample-malformed-short-header.txt
- api/src/test/resources/sample-malformed-short-trailer.txt
Jira: EDX-1333
Related: EDX-1307
> Improve file upload validations and add more tests

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/impl/NumberOfCoursesRule.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/impl/SupportBlocksRules.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/util/TransformUtil.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/rules/RulesProcessorTest.java
> Fix parser responsible for course counts

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/orchestrator/SdcStudentProcessingOrchestrator.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/repository/v1/SdcSchoolCollectionStudentRepository.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/programelegibilityimpl/NoInactiveOnlineAdultStudentsRule.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/programelegibilityimpl/NoInactiveOnlineMinorStudentsRule.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentService.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentServiceTest.java
Jira: EDX-1261
Rel: https://github.com/bcgov/EDUC-STUDENT-DATA-COLLECTION-API/pull/193
Details in the commit messages.
> Implement feedback from peer review

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/batch/validator/SdcFileValidator.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/orchestrator/SdcStudentProcessingOrchestrator.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/programelegibilityimpl/NoInactiveOnlineAdultStudentsRule.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentService.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcFileControllerTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/orchestrator/SdcStudentProcessingOrchestratorTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentServiceTest.java
- Makes it so sdc student is updated after changes in calculateAdditionalStudentAttributes are finished
> - Fixes null pointer error

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/constants/SdcSchoolCollectionStudentProgramEligibilityIssueCode.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/ProgramEligibilityBaseRule.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/programelegibilityimpl/FrenchStudentsMustBeEnrolled.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentService.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/rules/ProgramEligibilityRulesProcessorTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentServiceTest.java
> Add eligibility rule test for French programming and tests

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/constants/SdcSchoolCollectionStudentProgramEligibilityIssueCode.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/programelegibilityimpl/CareerProgramStudentsMustBeEnrolled.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentService.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/rules/ProgramEligibilityRulesProcessorTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentServiceTest.java
> Add career program role enrollment eligibility rule

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/calculator/FteCalculatorUtils.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/calculator/impl/AdultStudentCalculator.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/calculator/impl/AlternateProgramsCalculator.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/calculator/impl/StudentGraduatedCalculator.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/constants/SdcSchoolCollectionStudentProgramEligibilityIssueCode.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/helpers/BooleanString.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/programelegibilityimpl/NoInactiveOnlineAdultStudentsRule.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/programelegibilityimpl/NoInactiveOnlineMinorStudentsRule.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/programelegibilityimpl/SpecialEdStudentsMustBeSchoolAgeOrNotGraduated.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/programelegibilityimpl/SpecialEdStudentsMustRequireSpecialEd.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentService.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/struct/v1/BaseSdcSchoolStudent.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/BaseStudentDataCollectionAPITest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/calculator/FteCalculatorChainProcessorIntegrationTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/calculator/FteCalculatorUtilsTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/calculator/impl/AdultStudentCalculatorTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/calculator/impl/AlternateProgramsCalculatorTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/calculator/impl/StudentGraduatedCalculatorTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/helpers/BooleanStringTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/rules/ProgramEligibilityRulesProcessorTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentServiceTest.java
> Add program eligibility rules for special education programs

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/validationrules/impl/IndigenousProgramRule.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/validationrules/impl/SummerSchoolGradeRule.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/ValidationRulesService.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/rules/ProgramEligibilityRulesProcessorTest.java
HS grade not allowed in summer collection fix
> Allow null enrolled program codes for eligibilty

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/batch/service/SdcFileService.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcSchoolCollectionStudentController.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/mappers/v1/SdcSchoolCollectionStudentDecorator.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/mappers/v1/SdcStudentEllMapper.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/model/v1/SdcSchoolCollectionStudentEntity.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/model/v1/SdcSchoolCollectionStudentPaginationEntity.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/model/v1/SdcStudentEllEntity.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/orchestrator/SdcStudentProcessingOrchestrator.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/repository/v1/SdcSchoolCollectionStudentRepository.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentService.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/struct/v1/SdcSchoolCollectionStudent.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/BaseStudentDataCollectionAPITest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcSchoolCollectionStudentControllerTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/rules/ProgramEligibilityRulesProcessorTest.java
> Add SdcStudentEll data to paginated collection student queries

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/helpers/EllHeadcountHelper.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/calculator/impl/TooYoungCalculatorTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcSchoolCollectionStudentControllerTest.java
Jira: EDX-1429
This pull request fixes the orderedTitles for SummaryView headers for the ELL headcount summary view.  It also fixes a bug with one of our FTE tests.
> Bugfixes for SummaryView data.

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/helpers/EllHeadcountHelper.java
> fix: section & row titles for ELL summary

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/repository/v1/SdcSchoolCollectionStudentRepository.java
> fix: incorrect program code for career program totals

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcSchoolCollectionController.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionService.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcSchoolCollectionControllerTest.java
> Write student enrolled program codes when posting create school collection by ID

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcSchoolCollectionStudentController.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/endpoint/v1/SdcSchoolCollectionStudentEndpoint.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/model/v1/SdcStudentEllEntity.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentService.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcSchoolCollectionStudentControllerTest.java
> feature: add endpoint for creating SdcStudentElls

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcSchoolCollectionStudentController.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentService.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcSchoolCollectionStudentControllerTest.java
> fix: return ells when they already exist

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/repository/v1/SdcSchoolCollectionStudentRepository.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentService.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/BaseStudentDataCollectionAPITest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcSchoolCollectionControllerTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcSchoolCollectionStudentControllerTest.java
> Fix validation issue severity count summaries

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcDistrictCollectionController.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/endpoint/v1/SdcDistrictCollectionEndpoint.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/mappers/v1/SdcDistrictCollectionMapper.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcDistrictCollectionService.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/struct/v1/SdcDistrictCollection.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/util/ValidationUtil.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/validator/SdcDistrictCollectionValidator.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcDistrictCollectionControllerTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/validator/SdcDistrictCollectionValidatorTest.java
- tools/config/update-configmap.sh
EDX-1751 - Adds submissionDate to sdcDistrict struct to fix bug of missing submission date on district collection view
> EDX-1750, EDX-1752, EDX-1766 - Adds endpoints for seeding AT dat

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentService.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcSchoolCollectionStudentServiceTest.java
do not save if prov duplicate would be created - after validations pass
> MIN-Search and Edit Students in open collection

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/helpers/BandResidenceHeadcountHelper.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/helpers/CareerHeadcountHelper.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/helpers/CsfFrenchHeadcountHelper.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/helpers/EllHeadcountHelper.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/helpers/EnrollmentHeadcountHelper.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/helpers/FrenchCombinedHeadcountHelper.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/helpers/FrenchHeadcountHelper.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/helpers/HeadcountHelper.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/helpers/IndigenousHeadcountHelper.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/helpers/RefugeeHeadcountHelper.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/helpers/SpecialEdHeadcountHelper.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcDistrictCollectionHeadcountService.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/helpers/CareerHeadcountHelperTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/helpers/EllHeadcountHelperTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/helpers/EnrollmentHeadcountHelperTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/helpers/RefugeeHeadcountHelperTest.java
also fixing compare for enrollment and career
> add all schools to per school reports even if no results

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/constants/StudentValidationIssueTypeCode.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/constants/v1/ValidationRulesDependencyMatrix.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/repository/v1/SdcSchoolCollectionStudentRepository.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/validationrules/impl/SummerStudentOnlineLearningRule.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/validationrules/impl/SummerStudentReportedInDistrictRule.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/ValidationRulesService.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/rules/SummerRulesProcessorTest.java
Overview:
1. Changes to rule v93
2. New rule inclusion for 8/9
3. Changes to improve query performance for rule v93 & V99.
Unit Testing:
1. Upload File
2. School & District permission changes
3. Add student to validate v93 & v102 ACs.
> v93 rule change + Inclusion of v102 for 8/9

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/helpers/EllHeadcountHelper.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/reports/EllHeadcountPerSchoolReportService.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/reports/EllHeadcountReportService.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/repository/v1/SdcSchoolCollectionStudentRepository.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/struct/v1/headcounts/EllHeadcountHeaderResult.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/struct/v1/headcounts/EllHeadcountResult.java
- api/src/main/resources/reports/ellHeadcounts.jrxml
- api/src/main/resources/reports/ellHeadcountsPerSchool.jrxml
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/helpers/EllHeadcountHelperTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/repository/SdcSchoolCollectionStudentRepositoryTest.java
change all dis ell summaries, reports and headcounts to include breakdown of eligible vs ineligible instead of just all
> UAT-DIS-ELL Report updates to include ineligible students

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/constants/StudentValidationIssueTypeCode.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/ValidationBaseRule.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/validationrules/impl/SchoolAgedSpedRule.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/rules/RulesProcessorTest.java
Description: 
Changes to fix the defects on V79 rule execution
Unit Testing:
1. General Regression
2. ACs of  V79.
> Fix for reported issue.

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/constants/v1/ministryreports/IndySpecialEducationHeadcountHeader.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/constants/v1/ministryreports/SpecialEducationHeadcountHeader.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/repository/v1/SdcSchoolCollectionStudentRepository.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/reports/CSVReportService.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/reports/MinistryHeadcountService.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/struct/v1/headcounts/IndySpecialEdAdultHeadcountResult.java
Change Details:
- Mincode
- Authority
- Inclusive Education levels
Unit Testing:
- Generation of report
- CSV download.
> Changes to 2917

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/validationrules/impl/SummerStudentReportedInOtherDistrictRule.java
Description:
Change from error to funding warning.
Unit Testing:
General Regression.
> Changes to show V99 as warning instead of error.

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/repository/v1/impl/SdcSchoolCollectionStudentPaginationRepositoryLightImpl.java
sort = { sdcSchoolCollection: 'DESC' }; causing issues with warning filter on all students dis report
> adjust paginated slice cb sort to work for sdcSchoolCollection

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/reports/AllStudentLightCollectionGenerateCsvService.java
Unit Testing:
- General regression of upload file
- Download file and verify content for completion.
> Changes to avoid data truncation.

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/schedulers/EventTaskScheduler.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/events/schedulers/EventTaskSchedulerAsyncService.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/schedulers/EventTaskSchedulerTest.java
Changes to delete the closed school data
Unit Test cases
1. Check closed school collection data retained for PROVDUPE
2.  Check closed school  collection data removed states other than PROVDUPE.
> Changes to delete closed school collection data.

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/rules/validationrules/impl/SummerStudentOnlineLearningRule.java
Change description
1. Changes to check FTE of zero for v102.
> EDX-3011 - v102 changes.

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/reports/CSVReportService.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/util/TransformUtil.java
Unit Testing:
1. General regression to verify the FTE values.
> Changes to FTE positive change calculation.

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/events/schedulers/EventTaskSchedulerAsyncService.java
Details:
Changes to lookup allschools service to filter closed schools.
Unit Testing:
ACs
General regression on collection.
> EDX-2965: Changes to lookup allschools service to filter closed schools.

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcDuplicatesService.java
Description: Changes to avoid overriding the history data during PROVDUPES.
Unit Testing:
General regression.
> EDX:3082 Changes to avoid overriding the history data during PROVDUPES.

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/SdcDuplicateResolutionService.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/calculator/FteCalculatorChainProcessorIntegrationTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/controller/v1/SdcSchoolCollectionStudentControllerTest.java
- api/src/test/java/ca/bc/gov/educ/studentdatacollection/api/rules/SummerRulesProcessorTest.java
Description: Changes to retain the highest class and delete the lowest.
Unit Testing:
- ACs.
> Fix for duplicate resolution (based on class).

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/reports/AllStudentLightCollectionGenerateCsvService.java
- use 1 instead of Y in errors and warnings report
> DIS User | Minor Issues

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/repository/v1/SdcSchoolCollectionStudentFsaReportRepository.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/reports/CSVReportService.java
- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/service/v1/reports/MinistryHeadcountService.java
This reverts commit fa9e22b4687501d127cde3874e948e91936c4c11.
> Revert fsa pagination

- api/src/main/java/ca/bc/gov/educ/studentdatacollection/api/repository/v1/SdcSchoolCollectionStudentRepository.java
this is the same as the aggregate report
> OL/Funded report to check sscs.schoolFundingCode is null
